import Image from "next/image";
import Link from "next/link";
import { Activity, ArrowRight, Building2, CalendarDays, Check, FlaskConical, HeartPulse, MapPin, MessageCircle, Microscope, ShieldCheck, Stethoscope, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { ServiceCard } from "@/components/service-card";

export default function Home() {
  const shortcuts = [[Stethoscope, "Consultas", "Mais de 25 especialidades", "/consultas"], [Microscope, "Exames", "Diagnóstico com tecnologia", "/exames"], [UsersRound, "Corpo clínico", "Especialistas qualificados", "/corpo-clinico"], [MapPin, "Unidades", "Atendimento perto de você", "/unidades"]] as const;
  const units = [["Duque de Caxias", "Rua Dr. Arruda Negreiros, 11 — Centro", "Segunda a sexta, 7h30 às 17h30"], ["São João de Meriti", "Av. Automóvel Clube, 63 — Centro", "Segunda a sexta, 7h às 17h; sábado, 7h às 14h"], ["Centro do Rio", "Av. Rio Branco, 156 — Sala 2216", "Segunda a sexta, 8h às 17h"]];
  return <div className="flex min-h-screen flex-col bg-page text-slate-700"><SiteHeader /><main>
    <section className="relative isolate overflow-hidden bg-navy text-white"><Image src="/apice/hero.jpg" alt="Casal maduro sorrindo em um ambiente acolhedor" fill priority className="object-cover object-center opacity-45" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#0f286f_0%,rgba(15,40,111,.92)_43%,rgba(15,40,111,.3)_100%)]" /><div className="absolute inset-0 hero-grid opacity-25" /><div className="site-container relative grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div className="max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[.14em] backdrop-blur"><ShieldCheck className="size-4 text-orange" /> Saúde que acolhe. Estrutura que resolve.</p><h1 className="max-w-3xl text-4xl font-black leading-[1.08] tracking-[-.04em] sm:text-5xl lg:text-[64px]">Cuidado completo, tecnologia e confiança em cada etapa</h1><p className="mt-6 max-w-2xl text-base leading-7 text-blue-100 sm:text-xl sm:leading-8">Consultas, exames, terapias e procedimentos com equipes especializadas e unidades preparadas para cuidar de você e da sua família.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild className="h-14 rounded-xl bg-orange px-7 text-base font-black text-white shadow-xl shadow-black/20 hover:bg-orange-hover"><a href="https://wa.me/552136683131" target="_blank" rel="noreferrer"><CalendarDays className="size-5" /> Agendar atendimento</a></Button><Button asChild variant="outline" className="h-14 rounded-xl border-white/25 bg-white/10 px-7 text-base font-bold text-white backdrop-blur hover:bg-white hover:text-navy"><Link href="/unidades"><MapPin className="size-5" /> Encontrar uma unidade</Link></Button></div></div><aside className="hidden justify-self-end rounded-3xl border border-white/20 bg-white/95 p-7 text-navy shadow-2xl backdrop-blur lg:block lg:w-[360px]"><p className="text-xs font-black uppercase tracking-[.16em] text-orange">Central de atendimento</p><h2 className="mt-3 text-2xl font-black tracking-tight">Como podemos cuidar de você hoje?</h2><div className="mt-6 space-y-3">{[["Agendar uma consulta", "/consultas"], ["Informações sobre exames", "/exames"], ["Conhecer nossos planos", "/planos"]].map(([item, href]) => <Link key={item} href={href} className="flex items-center justify-between rounded-xl border border-slate-100 bg-white px-4 py-3 text-sm font-bold shadow-sm transition hover:border-orange/30 hover:text-orange"><span>{item}</span><ArrowRight className="size-4" /></Link>)}</div></aside></div></section>
    <section className="relative z-10 -mt-8 pb-10"><div className="site-container grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{shortcuts.map(([Icon, title, subtitle, href]) => <Link key={title} href={href} className="group flex items-center gap-4 rounded-2xl border border-slate-100 bg-white p-4 shadow-xl shadow-navy/8 transition hover:-translate-y-1 hover:border-orange/25"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-orange-soft text-orange"><Icon className="size-5" /></span><span><strong className="block text-sm font-black text-navy group-hover:text-orange">{title}</strong><span className="text-xs text-slate-500">{subtitle}</span></span></Link>)}</div></section>
    <section className="py-20"><div className="site-container"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="eyebrow">Cuidado integrado</p><h2 className="section-title">Uma rede completa para todas as fases da sua saúde</h2><p className="section-subtitle">Da prevenção ao diagnóstico e tratamento, encontre cuidado coordenado em um só lugar.</p></div><Link href="/servicos" className="inline-flex items-center gap-2 font-extrabold text-navy hover:text-orange">Ver todos os serviços <ArrowRight className="size-4" /></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><ServiceCard icon={Stethoscope} title="Consultas médicas" description="Especialidades clínicas e cirúrgicas com atendimento acolhedor." href="/consultas" eyebrow="Prevenção" /><ServiceCard icon={FlaskConical} title="Exames" description="Medicina diagnóstica, laboratório e imagem com tecnologia avançada." href="/exames" eyebrow="Diagnóstico" /><ServiceCard icon={HeartPulse} title="Terapias" description="Cuidado em saúde mental, fisioterapia e reabilitação." href="/terapias" eyebrow="Acompanhamento" /><ServiceCard icon={Activity} title="Procedimentos" description="Estrutura preparada para procedimentos ambulatoriais e cirúrgicos." href="/cirurgias" eyebrow="Resolutividade" /></div></div></section>
    <section className="bg-navy py-18 text-white"><div className="site-container grid gap-10 md:grid-cols-4">{[["20+", "anos de experiência"], ["25+", "especialidades"], ["2.000+", "exames laboratoriais"], ["3", "unidades apresentadas"]].map(([number, label]) => <div key={label} className="border-l-2 border-orange pl-5"><strong className="block text-4xl font-black tracking-tight">{number}</strong><span className="mt-1 block text-sm text-blue-200">{label}</span></div>)}</div></section>
    <section className="overflow-hidden bg-section py-20"><div className="site-container grid items-center gap-12 lg:grid-cols-2"><div className="relative min-h-[480px] overflow-hidden rounded-[32px] shadow-2xl shadow-navy/15"><Image src="/apice/diagnostico.jpg" alt="Tecnologia de diagnóstico da Ápice Saúde" fill className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-navy/55 to-transparent" /><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/20 bg-white/92 p-5 backdrop-blur"><p className="flex items-center gap-2 text-sm font-black text-navy"><ShieldCheck className="size-5 text-orange" /> Excelência clínica com acolhimento</p></div></div><div><p className="eyebrow">Estrutura hospitalar</p><h2 className="section-title">Tecnologia que amplia a precisão. Pessoas que tornam o cuidado humano.</h2><p className="section-subtitle">A Ápice combina equipamentos modernos, profissionais especializados e uma jornada mais simples para oferecer segurança do primeiro contato ao resultado.</p><ul className="mt-7 grid gap-4 sm:grid-cols-2">{["Tomografia computadorizada", "Exames laboratoriais", "Centro cirúrgico", "Atendimento multiprofissional"].map(item => <li key={item} className="flex items-center gap-3 text-sm font-bold text-navy"><span className="grid size-6 place-items-center rounded-full bg-orange-soft text-orange"><Check className="size-4" /></span>{item}</li>)}</ul><Button asChild className="mt-9 h-12 rounded-xl bg-navy px-6 font-extrabold text-white hover:bg-navy-hover"><Link href="/exames">Conhecer estrutura diagnóstica <ArrowRight /></Link></Button></div></div></section>
    <section className="py-20"><div className="site-container"><div className="text-center"><p className="eyebrow">Onde estamos</p><h2 className="section-title">Unidades preparadas para receber você</h2><p className="section-subtitle mx-auto">Encontre endereços, horários e o melhor canal de atendimento.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{units.map(([name, address, hours]) => <article key={name} className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-navy text-white"><Building2 className="size-5" /></span><h3 className="mt-6 text-xl font-black text-navy">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{address}</p><p className="mt-4 border-t border-slate-100 pt-4 text-xs font-semibold leading-5 text-slate-500">{hours}</p><Link href="/unidades" className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-orange">Ver detalhes <ArrowRight className="size-4" /></Link></article>)}</div></div></section>
    <section className="pb-20"><div className="site-container"><div className="relative overflow-hidden rounded-[32px] bg-orange px-6 py-12 text-white shadow-xl shadow-orange/15 sm:px-12 lg:flex lg:items-center lg:justify-between"><div className="absolute -right-20 -top-28 size-72 rounded-full border-[48px] border-white/10" /><div className="relative max-w-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-white/75">Atendimento fácil e direto</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Pronto para cuidar da sua saúde?</h2><p className="mt-3 text-white/85">Fale com nossa equipe para agendar consultas e obter orientações sobre exames.</p></div><Button asChild className="relative mt-7 h-14 rounded-xl bg-white px-7 font-black text-navy hover:bg-navy hover:text-white lg:mt-0"><a href="https://wa.me/552136683131" target="_blank" rel="noreferrer"><MessageCircle /> Falar no WhatsApp</a></Button></div></div></section>
  </main><SiteFooter /></div>;
}
