import Image from "next/image";
import { Briefcase, Camera, Globe2, MapPin, Phone, Play } from "lucide-react";

export function SiteFooter() {
  const socials = [[Globe2, "https://www.facebook.com/apicesaude", "Facebook"], [Camera, "https://www.instagram.com/saudeapice/", "Instagram"], [Play, "https://www.youtube.com/@saudeapice1364", "YouTube"], [Briefcase, "https://www.linkedin.com/company/saude-apice/", "LinkedIn"]] as const;
  return <footer className="relative mt-auto overflow-hidden rounded-tr-[40px] bg-navy text-indigo-200"><div aria-hidden="true" className="absolute left-0 top-0 h-1.5 w-3/4 bg-orange" /><div className="site-container grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-4">
    <div><Image src="/apice/logo-reverse.png" alt="Ápice Saúde" width={230} height={46} className="mb-6 h-auto w-[210px] object-contain" /><p className="max-w-xs text-sm leading-6 text-indigo-100/75">Há mais de 20 anos unindo cuidado humano, especialistas e tecnologia para oferecer uma experiência de saúde completa.</p></div>
    <div><h2 className="mb-4 text-sm font-black uppercase tracking-widest text-white">Atendimento</h2><ul className="space-y-3 text-sm"><li><a className="footer-link" href="tel:+552136683131" aria-label="Ligar para agendamento no número 21 3668-3131"><Phone className="size-4 text-orange" /> Agendamento: (21) 3668-3131</a></li><li><a className="footer-link" href="tel:+552136683100" aria-label="Ligar para atendimento de planos no número 21 3668-3100"><Phone className="size-4 text-orange" /> Planos: (21) 3668-3100</a></li><li><a className="footer-link" href="/unidades"><MapPin className="size-4 text-orange" /> Ver nossas unidades</a></li></ul></div>
    <div><h2 className="mb-4 text-sm font-black uppercase tracking-widest text-white">Acesso rápido</h2><nav aria-label="Acesso rápido do rodapé" className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><a className="hover:text-white" href="/consultas">Consultas</a><a className="hover:text-white" href="/exames">Exames</a><a className="hover:text-white" href="/unidades">Unidades</a><a className="hover:text-white" href="/planos">Planos</a><a className="hover:text-white" href="/institucional">Institucional</a><a className="hover:text-white" href="/contato">Contato</a></nav></div>
    <div><h2 className="mb-4 text-sm font-black uppercase tracking-widest text-white">Siga a Ápice</h2><div className="flex gap-2">{socials.map(([Icon, href, label]) => <a key={label} href={href} aria-label={label} target="_blank" rel="noreferrer" className="grid size-10 place-items-center rounded-xl bg-white/8 text-white transition hover:-translate-y-0.5 hover:bg-orange"><Icon className="size-4" /></a>)}</div></div>
  </div><div className="border-t border-white/10"><div className="site-container flex flex-col items-center justify-center gap-2 py-6 text-center text-xs text-indigo-200/70"><p>© 2026 Ápice Saúde. Todos os direitos reservados.</p><p>CNPJ 05.048.983/0001-50</p><p className="font-black text-orange">Desenvolvido por Íon Digital</p></div></div></footer>;
}
